// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int mustbeon_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int mustbeon = 10;
	/// <summary>PID: 20 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int mustnotbevacation_20 = 20;
	/// <summary>PID: 20 | Type: read</summary>
	public const int mustnotbevacation = 20;
	/// <summary>PID: 30 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int mustequalworking_30 = 30;
	/// <summary>PID: 30 | Type: read</summary>
	public const int mustequalworking = 30;
	public class Write
	{
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int mustbeon_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int mustbeon = 110;
		/// <summary>PID: 120 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int mustnotbevacation_120 = 120;
		/// <summary>PID: 120 | Type: write</summary>
		public const int mustnotbevacation = 120;
		/// <summary>PID: 130 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int mustequalworking_130 = 130;
		/// <summary>PID: 130 | Type: write</summary>
		public const int mustequalworking = 130;
		/// <summary>PID: 1053 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingmanagerperiod_1053 = 1053;
		/// <summary>PID: 1053 | Type: write</summary>
		public const int pollingmanagerperiod = 1053;
		/// <summary>PID: 1055 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingmanagerperiodtype_1055 = 1055;
		/// <summary>PID: 1055 | Type: write</summary>
		public const int pollingmanagerperiodtype = 1055;
		/// <summary>PID: 1100 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int pollingmanager_contextmenu_1100 = 1100;
		/// <summary>PID: 1100 | Type: write</summary>
		public const int pollingmanager_contextmenu = 1100;
	}
	public class Pollingmanager
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerindex_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int pollingmanagerindex = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagername_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int pollingmanagername = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerperiod_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int pollingmanagerperiod = 1003;
			/// <summary>PID: 1004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerdefaultperiod_1004 = 1004;
			/// <summary>PID: 1004 | Type: read</summary>
			public const int pollingmanagerdefaultperiod = 1004;
			/// <summary>PID: 1005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerperiodtype_1005 = 1005;
			/// <summary>PID: 1005 | Type: read</summary>
			public const int pollingmanagerperiodtype = 1005;
			/// <summary>PID: 1006 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerlastpoll_1006 = 1006;
			/// <summary>PID: 1006 | Type: read</summary>
			public const int pollingmanagerlastpoll = 1006;
			/// <summary>PID: 1007 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerstatus_1007 = 1007;
			/// <summary>PID: 1007 | Type: read</summary>
			public const int pollingmanagerstatus = 1007;
			/// <summary>PID: 1008 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerreason_1008 = 1008;
			/// <summary>PID: 1008 | Type: read</summary>
			public const int pollingmanagerreason = 1008;
			/// <summary>PID: 1010 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerstate_1010 = 1010;
			/// <summary>PID: 1010 | Type: read</summary>
			public const int pollingmanagerstate = 1010;
			/// <summary>PID: 1099 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerdisplaykey_1099 = 1099;
			/// <summary>PID: 1099 | Type: read</summary>
			public const int pollingmanagerdisplaykey = 1099;
			public class Write
			{
				/// <summary>PID: 1059 | Type: write</summary>
				[EditorBrowsable(EditorBrowsableState.Never)]
				public const int pollingmanagerpoll_1059 = 1059;
				/// <summary>PID: 1059 | Type: write</summary>
				public const int pollingmanagerpoll = 1059;
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerindex_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int pollingmanagerindex = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagername_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int pollingmanagername = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerperiod_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int pollingmanagerperiod = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerdefaultperiod_1004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int pollingmanagerdefaultperiod = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerperiodtype_1005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int pollingmanagerperiodtype = 4;
			/// <summary>IDX: 5 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerlastpoll_1006 = 5;
			/// <summary>IDX: 5 | Type: read</summary>
			public const int pollingmanagerlastpoll = 5;
			/// <summary>IDX: 6 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerstatus_1007 = 6;
			/// <summary>IDX: 6 | Type: read</summary>
			public const int pollingmanagerstatus = 6;
			/// <summary>IDX: 7 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerreason_1008 = 7;
			/// <summary>IDX: 7 | Type: read</summary>
			public const int pollingmanagerreason = 7;
			/// <summary>IDX: 9 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerstate_1010 = 9;
			/// <summary>IDX: 9 | Type: read</summary>
			public const int pollingmanagerstate = 9;
			/// <summary>IDX: 10 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int pollingmanagerdisplaykey_1099 = 10;
			/// <summary>IDX: 10 | Type: read</summary>
			public const int pollingmanagerdisplaykey = 10;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 110  | Type: write | DISCREETS: Off = 0, On = 1</summary>
	public System.Object Mustbeon {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	/// <summary>PID: 120  | Type: write | DISCREETS: Home = 1, Office = 2, Vacation = 3</summary>
	public System.Object Mustnotbevacation {get { return Protocol.GetParameter(120); }set { Protocol.SetParameter(120, value); }}
	/// <summary>PID: 130  | Type: write</summary>
	public System.Object Mustequalworking {get { return Protocol.GetParameter(130); }set { Protocol.SetParameter(130, value); }}
	/// <summary>PID: 1053  | Type: write</summary>
	public System.Object Pollingmanagerperiod {get { return Protocol.GetParameter(1053); }set { Protocol.SetParameter(1053, value); }}
	/// <summary>PID: 1055  | Type: write | DISCREETS: Default Period = 1, Custom Period = 2</summary>
	public System.Object Pollingmanagerperiodtype {get { return Protocol.GetParameter(1055); }set { Protocol.SetParameter(1055, value); }}
	/// <summary>PID: 1059  | Type: write | DISCREETS: Poll = 1</summary>
	public System.Object Pollingmanagerpoll {get { return Protocol.GetParameter(1059); }set { Protocol.SetParameter(1059, value); }}
	/// <summary>PID: 1100  | Type: write | DISCREETS: Poll All = 1, Separator 1 = -1, Disable = 2, Enable = 3, Force Disable = 4, Force Enable = 5, Separator 2 = -2, Disable All = 6, Enable All = 7</summary>
	public System.Object Pollingmanager_contextmenu {get { return Protocol.GetParameter(1100); }set { Protocol.SetParameter(1100, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 1000</summary>
	PollingmanagerQActionTable pollingmanager { get; set; }
	object Mustbeon_10 { get; set; }
	object Mustbeon { get; set; }
	object Mustnotbevacation_20 { get; set; }
	object Mustnotbevacation { get; set; }
	object Mustequalworking_30 { get; set; }
	object Mustequalworking { get; set; }
	object Mustbeon_110 { get; set; }
	object Mustnotbevacation_120 { get; set; }
	object Mustequalworking_130 { get; set; }
	object Pollingmanagerinit_dummy { get; set; }
	object Pollingmanagercheck_dummy { get; set; }
	object Pollingmanagerindex_1001 { get; set; }
	object Pollingmanagerindex { get; set; }
	object Pollingmanagername_1002 { get; set; }
	object Pollingmanagername { get; set; }
	object Pollingmanagerperiod_1003 { get; set; }
	object Pollingmanagerperiod { get; set; }
	object Pollingmanagerdefaultperiod_1004 { get; set; }
	object Pollingmanagerdefaultperiod { get; set; }
	object Pollingmanagerperiodtype_1005 { get; set; }
	object Pollingmanagerperiodtype { get; set; }
	object Pollingmanagerlastpoll_1006 { get; set; }
	object Pollingmanagerlastpoll { get; set; }
	object Pollingmanagerstatus_1007 { get; set; }
	object Pollingmanagerstatus { get; set; }
	object Pollingmanagerreason_1008 { get; set; }
	object Pollingmanagerreason { get; set; }
	object Pollingmanagerstate_1010 { get; set; }
	object Pollingmanagerstate { get; set; }
	object Pollingmanagerperiod_1053 { get; set; }
	object Pollingmanagerperiodtype_1055 { get; set; }
	object Pollingmanagerpoll_1059 { get; set; }
	object Pollingmanagerpoll { get; set; }
	object Pollingmanagerdisplaykey_1099 { get; set; }
	object Pollingmanagerdisplaykey { get; set; }
	object Pollingmanager_contextmenu_1100 { get; set; }
	object Pollingmanager_contextmenu { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1000</summary>
	public PollingmanagerQActionTable pollingmanager { get; set; }
	/// <summary>PID: 10  | Type: read | DISCREETS: Off = 0, On = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Mustbeon_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Off = 0, On = 1</summary>
	public System.Object Mustbeon {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 20  | Type: read | DISCREETS: Home = 1, Office = 2, Vacation = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Mustnotbevacation_20 {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 20  | Type: read | DISCREETS: Home = 1, Office = 2, Vacation = 3</summary>
	public System.Object Mustnotbevacation {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Mustequalworking_30 {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 30  | Type: read</summary>
	public System.Object Mustequalworking {get { return GetParameter(30); }set { SetParameter(30, value); }}
	/// <summary>PID: 110  | Type: write | DISCREETS: Off = 0, On = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Mustbeon_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 120  | Type: write | DISCREETS: Home = 1, Office = 2, Vacation = 3</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Mustnotbevacation_120 {get { return GetParameter(120); }set { SetParameter(120, value); }}
	/// <summary>PID: 130  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Mustequalworking_130 {get { return GetParameter(130); }set { SetParameter(130, value); }}
	/// <summary>PID: 998  | Type: dummy</summary>
	public System.Object Pollingmanagerinit_dummy {get { return GetParameter(998); }set { SetParameter(998, value); }}
	/// <summary>PID: 999  | Type: dummy</summary>
	public System.Object Pollingmanagercheck_dummy {get { return GetParameter(999); }set { SetParameter(999, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerindex_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Pollingmanagerindex {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagername_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Pollingmanagername {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerperiod_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object Pollingmanagerperiod {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerdefaultperiod_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read</summary>
	public System.Object Pollingmanagerdefaultperiod {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read | DISCREETS: Default Period = 1, Custom Period = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerperiodtype_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read | DISCREETS: Default Period = 1, Custom Period = 2</summary>
	public System.Object Pollingmanagerperiodtype {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1006  | Type: read | EXCEPTIONS: Not Polled = -2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerlastpoll_1006 {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1006  | Type: read | EXCEPTIONS: Not Polled = -2</summary>
	public System.Object Pollingmanagerlastpoll {get { return GetParameter(1006); }set { SetParameter(1006, value); }}
	/// <summary>PID: 1007  | Type: read | DISCREETS: Failed = 0, Succeeded = 1 | EXCEPTIONS: Not Polled = -2, Disabled = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerstatus_1007 {get { return GetParameter(1007); }set { SetParameter(1007, value); }}
	/// <summary>PID: 1007  | Type: read | DISCREETS: Failed = 0, Succeeded = 1 | EXCEPTIONS: Not Polled = -2, Disabled = -1</summary>
	public System.Object Pollingmanagerstatus {get { return GetParameter(1007); }set { SetParameter(1007, value); }}
	/// <summary>PID: 1008  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerreason_1008 {get { return GetParameter(1008); }set { SetParameter(1008, value); }}
	/// <summary>PID: 1008  | Type: read</summary>
	public System.Object Pollingmanagerreason {get { return GetParameter(1008); }set { SetParameter(1008, value); }}
	/// <summary>PID: 1010  | Type: read | DISCREETS: Disabled = 1, Enabled = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerstate_1010 {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1010  | Type: read | DISCREETS: Disabled = 1, Enabled = 2</summary>
	public System.Object Pollingmanagerstate {get { return GetParameter(1010); }set { SetParameter(1010, value); }}
	/// <summary>PID: 1053  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerperiod_1053 {get { return GetParameter(1053); }set { SetParameter(1053, value); }}
	/// <summary>PID: 1055  | Type: write | DISCREETS: Default Period = 1, Custom Period = 2</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerperiodtype_1055 {get { return GetParameter(1055); }set { SetParameter(1055, value); }}
	/// <summary>PID: 1059  | Type: write | DISCREETS: Poll = 1</summary>
	public System.Object Pollingmanagerpoll_1059 {get { return GetParameter(1059); }set { SetParameter(1059, value); }}
	/// <summary>PID: 1059  | Type: write | DISCREETS: Poll = 1</summary>
	public System.Object Pollingmanagerpoll {get { return Write.Pollingmanagerpoll; }set { Write.Pollingmanagerpoll = value; }}
	/// <summary>PID: 1099  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerdisplaykey_1099 {get { return GetParameter(1099); }set { SetParameter(1099, value); }}
	/// <summary>PID: 1099  | Type: read</summary>
	public System.Object Pollingmanagerdisplaykey {get { return GetParameter(1099); }set { SetParameter(1099, value); }}
	/// <summary>PID: 1100  | Type: write | DISCREETS: Poll All = 1, Separator 1 = -1, Disable = 2, Enable = 3, Force Disable = 4, Force Enable = 5, Separator 2 = -2, Disable All = 6, Enable All = 7</summary>
	public System.Object Pollingmanager_contextmenu_1100 {get { return GetParameter(1100); }set { SetParameter(1100, value); }}
	/// <summary>PID: 1100  | Type: write | DISCREETS: Poll All = 1, Separator 1 = -1, Disable = 2, Enable = 3, Force Disable = 4, Force Enable = 5, Separator 2 = -2, Disable All = 6, Enable All = 7</summary>
	public System.Object Pollingmanager_contextmenu {get { return Write.Pollingmanager_contextmenu; }set { Write.Pollingmanager_contextmenu = value; }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		pollingmanager = new PollingmanagerQActionTable(this, 1000, "pollingmanager");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class PollingmanagerQActionTable : QActionTable, IEnumerable<PollingmanagerQActionRow>
{
	public PollingmanagerQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<PollingmanagerQActionRow> GetEnumerator() { return new QActionTableEnumerator<PollingmanagerQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class PollingmanagerQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerindex_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Pollingmanagerindex { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagername_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Pollingmanagername { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerperiod_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object Pollingmanagerperiod { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerdefaultperiod_1004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	public System.Object Pollingmanagerdefaultperiod { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerperiodtype_1005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	public System.Object Pollingmanagerperiodtype { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1006 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerlastpoll_1006 { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 1006 | Type: read</summary>
	public System.Object Pollingmanagerlastpoll { get { if (base.Columns.ContainsKey(5)) { return base.Columns[5]; } else { return null; } } set { if (base.Columns.ContainsKey(5)) { base.Columns[5] = value; } else { base.Columns.Add(5, value); } } }
	/// <summary>PID: 1007 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerstatus_1007 { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 1007 | Type: read</summary>
	public System.Object Pollingmanagerstatus { get { if (base.Columns.ContainsKey(6)) { return base.Columns[6]; } else { return null; } } set { if (base.Columns.ContainsKey(6)) { base.Columns[6] = value; } else { base.Columns.Add(6, value); } } }
	/// <summary>PID: 1008 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerreason_1008 { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 1008 | Type: read</summary>
	public System.Object Pollingmanagerreason { get { if (base.Columns.ContainsKey(7)) { return base.Columns[7]; } else { return null; } } set { if (base.Columns.ContainsKey(7)) { base.Columns[7] = value; } else { base.Columns.Add(7, value); } } }
	/// <summary>PID: 1059 | Type: write</summary>
	public System.Object Pollingmanagerpoll_1059 { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
	/// <summary>PID: 1059 | Type: write</summary>
	public System.Object Pollingmanagerpoll { get { if (base.Columns.ContainsKey(8)) { return base.Columns[8]; } else { return null; } } set { if (base.Columns.ContainsKey(8)) { base.Columns[8] = value; } else { base.Columns.Add(8, value); } } }
	/// <summary>PID: 1010 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerstate_1010 { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
	/// <summary>PID: 1010 | Type: read</summary>
	public System.Object Pollingmanagerstate { get { if (base.Columns.ContainsKey(9)) { return base.Columns[9]; } else { return null; } } set { if (base.Columns.ContainsKey(9)) { base.Columns[9] = value; } else { base.Columns.Add(9, value); } } }
	/// <summary>PID: 1099 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Pollingmanagerdisplaykey_1099 { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
	/// <summary>PID: 1099 | Type: read</summary>
	public System.Object Pollingmanagerdisplaykey { get { if (base.Columns.ContainsKey(10)) { return base.Columns[10]; } else { return null; } } set { if (base.Columns.ContainsKey(10)) { base.Columns[10] = value; } else { base.Columns.Add(10, value); } } }
	public PollingmanagerQActionRow() : base(0, 11) { }
	public PollingmanagerQActionRow(System.Object[] oRow) : base(0, 11, oRow) { }
	public static implicit operator PollingmanagerQActionRow(System.Object[] source) { return new PollingmanagerQActionRow(source); }
	public static implicit operator System.Object[](PollingmanagerQActionRow source) { return source.ToObjectArray(); }
}
}
